### ISSUE TITLE
Usage of Images from your Website

### ISSUE THREAD

**Issue by snowsquizy** [ischlag/ischlag.github.io#2]
What is the usage license for the Images from your website.  Looking to use the distributed tensorflow diagram in my final year engineering project report.

**Comment by ischlag** [comment]
Hi

The image is from the TensorFlow whitepaper: http://download.tensorflow.org/paper/whitepaper2015.pdf 
I didn't see this paper listed under a Creative Commons license so I assume it is not. If you want to use the diagrams as they are in the paper you will have to cite that paper. The concept, however, I think is not subject to copyright. I will add such a reference to the article myself.
